### ISSUE TITLE
How restart slugify after edit column slug

### ISSUE THREAD

**Issue by Iyongbudiarso** [madflow/jquery-slugify#15]
That slugify is in modal, after I edit column slugify and I open again modal, that slugify not automatically again. So, how to restart that slugify again?

My code is like this
```javascript
$('body').on('click', '#add-bloggerUser', function(e){
            $('#blogger_slug').slugify('#blogger_name');
            $('#popup_blogger-form').modal('show');
            e.preventDefault();
});

$('body').on('click', '.update-bloggerUser', function(e){
            $('#blogger_slug').slugify('#blogger_name');
            $('#popup_blogger-form').modal('show');
            e.preventDefault();
});
```

Thank you

**Comment by madflow** [comment]
Sorry - I do not quite understand the use case here. Can you create a plunkr (http://plnkr.co/) with a minimal use case?

**Comment by Iyongbudiarso** [comment]
Sorry my bad english
can you check this video please
https://s.nimbus.everhelper.me/share/1162347/9p661q3bl8f03n1ad5pa

**Comment by madflow** [comment]
@Iyongbudiarso Thanks for the cool video 👍 I blindly fixed the issue - since I assumed that it was due to the fact, that the content of your modal is not destroyed when you click away when the modal closes.

Whenever you change the slugified field yourself - altering the source will have no effect on the slugified field.

This is done by setting a .data field like ```$target.data('locked', true);``` . This stays the same - since the DOM does not change. After that - your changes will have no effect when you re-open the modal.

I commited a test and a fix into ```master``` branch. I just asserted that a target field can never be "locked" when it is empty and the source field is changed...

Since I am not sure how you include the script: You can use the latest master for testing or:

https://cdn.rawgit.com/madflow/jquery-slugify/master/dist/slugify.min.js

Please test my changes if this resolves your issue. Maybe I missed something...

**Comment by Iyongbudiarso** [comment]
Thats perfect. ok @madflow thanks for the advice :1st_place_medal: My problem is solved.

Thank you
